services:
  app:
    build:
      context: .
      dockerfile: ./.devops/php/Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - thumb
networks:
  thumb:
    driver: bridge