#!/usr/bin/env php
<?php

declare(strict_types=1);

use Thiiagoms\Thumb\App;
use Thiiagoms\Thumb\Utils\Banner;
use Thiiagoms\Thumb\Utils\Printer;

if (php_sapi_name() !== 'cli') {
    echo '<h1>Only in CLI mode</h1>';
    exit;
}

require __DIR__.'/bootstrap.php';

Banner::banner();

if (isset($argv[1]) && in_array($argv[1], ['-h', '--help', '-help'])) {
    Banner::help();
    exit;
}

$url = readline('👉Youtube URL: ');

/** @var \DI\Container $container */
$app = $container->get(App::class);

$code = $app->with($url)->handle();

Printer::success("
    🎉Youtube code: {$code}
    🚀Check you thumb under storage/images with Youtube code {$code}
");
